Added the ability to specify the channels Ids
voidbar/forwardgram pull request #27
Opened 2021-02-21 22:31 UTC by abdellahaski

2021-02-25 12:00 UTC, voidbar requested changes
Thanks for the contribution! was thinking about adding it myself! seems ok but I have few small comments

2021-02-25 12:00 UTC, voidbar commented on config.yml-sample
> +  - 'Input Channel ID 1' # without quotes ''
remove quotes from the examples

2021-02-25 12:00 UTC, voidbar commented on config.yml-sample
> +# The channel IDs that you'd like to forward messages from. (You can get a channel ID by forwarding any message from it to @userinfobot , and removing the -100 from the start )
give example for how to set this list as an empty one. i.e: `input_channel_ids: []`

2021-02-25 20:21 UTC, abdellahaski commented
@voidbar you're welcome, I just committed the edits that you requested

2021-03-06 20:36 UTC, merged

2021-04-22 01:35 UTC, jerung3000 commented
Hi voidbar

When I run this repo..Igot error like this..

Traceback (most recent call last):
  File "C:\PYTHON\forwardgram\forwardgram\forwardgram.py", line 49, in <module>
    start(config)
  File "C:\PYTHON\forwardgram\forwardgram\forwardgram.py", line 22, in start
    input_channels_entities.append(InputChannel(d.entity.id, d.entity.access_hash))
AttributeError: 'Chat' object has no attribute 'access_hash'

How solve this error..?Thank you..

2021-04-22 01:40 UTC, abdellahaski commented
@jerung3000 Can you open an issue, and include your config file (after removing your api_id/hash)